spring.application.name=tarea1

spring.datasource.url=jdbc:mariadb://localhost:3306/tareasDB
spring.datasource.username=root
spring.datasource.password=password

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver